@startuml
actor User
participant API
database DB
collections FS
|||
User -> API: Uploads .csv file
API -> FS: Save .csv file into temp directory
API --> User: Return temp file ID
...
User -> API: Temp file ID
API -> FS: Read temp file using standart csv_sniffer
User -> API: CSV Dialect 
API -> FS: Re-read temp file
User -> API: Temp file ID and correct dataset headers
API -> FS: Re-read temp file
API --> User: Return re-parsed header specification and temp ID
...
FS --> API: Bytes file content
API -> DB: Create Dataset model
DB --> API: Newly created model
API -> DB: Create CsvDialect model
DB --> API: Newly created model
|||
loop each column
    API -> DB: Create Column model
    DB --> API: Newly created model
    |||
API -> FS: Copy source file to MEDIA directory
API -> FS: Remove temp directory
API --> User: Return Dataset DTO
...
User -> API: Dataset ID
API -> DB: Get Dataset model
DB --> API: Dataset model
API --> FS: Read dataset file
API -> User: Dataset information, dialect and parsed dataset rows
|||
User -> API: Dataset ID, type of plot and parameters for Seaborn
User -> API: Dataset ID
API -> DB: Get Dataset model
API -> DB: Get hash digest of the Plot DTO
API --> FS: Read dataset file
FS --> API: Path of rendered plot image
API -> User: Return 'Content-Location' header with the route to plot image
|||
end
@enduml
